# Use root/example as user/password credentials
services:
  web:
    #    image: registry.gitlab.com/hexsagon/font_end
    image: back_end:1
    restart: always
    ports:
      - 3000:3000
    environment:
      - HOST=172.18.64.1
      - PASSWORD=null
      - USERNAME=root
      - DATABASE=test_upload_gambar
      - PORT_MYSQL=3306
      - SERVER=http://localhost:3000/
      - MYSQL=mysql
    volumes:
      - /public2:/app/public
